name: flodash
description: A dart implementation of the popular JavaScript library Lodash
version: 1.0.2
repository: https://github.com/sliit-foss/flodash

environment:
  sdk: ">=2.12.0 <3.7.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter