name: CI Tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - run: flutter pub get
      - run: flutter pub global run melos bootstrap
      - run: flutter pub global run melos exec --diff=$(git log --skip=1 -n 1 --pretty=format:"%H") -- flutter test